# Generated by Django 5.2.8 on 2025-11-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadorprofile',
            name='servicos',
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestadores', to='servicos.servico'),
        ),
    ]
