# Generated by Django 5.2.8 on 2025-12-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clienteprofile_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_clientes/'),
        ),
    ]
