# Generated by Django 5.2.8 on 2025-12-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_prestadorprofile_servicos_nao_realizados_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(help_text='CPF sem pontuação', max_length=11, null=True),
        ),
    ]
